spring:
  data:
    mongodb:
      authentication-database: admin
      username: rootuser
      password: rootpass
      database: viettq-db
      port: 27017
      host: localhost
      #auto indexed
      auto-index-creation: true